# Generated by Django 2.1.5 on 2019-02-14 09:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namediv', models.CharField(max_length=200, verbose_name='Phòng khám ')),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
            managers=[
                ('div', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Donthuoc',
            fields=[
                ('codedonthuoc', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code đơn thuốc')),
                ('codethuoc', models.CharField(default='', max_length=200, verbose_name='Code thuốc')),
                ('name_donthuoc', models.CharField(choices=[('Panadol', 'Panadol'), ('Vitamin C', 'Vitamin C'), ('Decongen', 'Decongen')], default='Panadol', max_length=200, verbose_name='Tên thuốc ')),
                ('soluong', models.CharField(default='1', max_length=200, verbose_name='Số lượng ')),
                ('dvtinh', models.CharField(default='vỉ', max_length=200, verbose_name='Đơn vị tính')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            managers=[
                ('Donthuoc1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ketluan',
            fields=[
                ('codeketluan', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code kết luận')),
                ('name_ketluan', models.TextField(blank=True, null=True, verbose_name='Kết luận ')),
                ('bacsy', models.CharField(max_length=200, verbose_name='Bác sỹ')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
            ],
            managers=[
                ('ketluan1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('codepatientp', models.CharField(default='BN1', max_length=10, primary_key=True, serialize=False, verbose_name='Code bệnh nhân')),
                ('namepatient', models.CharField(max_length=200, verbose_name='Họ tên')),
                ('age', models.IntegerField(default=40, verbose_name='Tuổi')),
                ('place', models.CharField(max_length=200, null=True, verbose_name='Địa chỉ')),
                ('City', models.CharField(choices=[('Hà Nội', 'Hà Nội'), ('Hà Nam', 'Hà Nam'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Hải Phòng', 'Hải Phòng'), ('Thái Bình', 'Thái Bình')], default='Hà Nội', max_length=200, null=True, verbose_name='Thành phố')),
                ('Type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Division')),
            ],
            managers=[
                ('pat', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Đã gửi yêu cầu', max_length=200, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Ngày yêu cầu dịch vụ')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
            ],
            managers=[
                ('serv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchung',
            fields=[
                ('codetrieuchung', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code triệu chứng')),
                ('trieuchung1', models.CharField(choices=[('Bất tỉnh', 'Bất tỉnh'), ('Mạch nhanh', 'Mạch nhanh'), ('Mạch chậm', 'Mạch chậm'), ('Tăng huyết áp tâm thu', 'Tăng huyết áp tâm thu'), ('tăng huyết áp tâm trường', 'tăng huyết áp tâm trường'), ('Mất máu', 'Mất máu'), ('Gẫy xương', 'Gẫy xương'), ('Giãn đồng tử', 'Giãn đồng tử')], default='Bất tỉnh', max_length=200, verbose_name='Triệu chứng')),
                ('nhomcoquan', models.CharField(choices=[('đầu', 'đầu'), ('tứ chi', 'tứ chi'), ('ngực', 'ngực'), ('hệ tuần hoàn', 'hệ tuần hoàn'), ('Hệ hô hấp', 'Hệ hô hấp')], default='Bất tỉnh', max_length=200, verbose_name='Nhóm cơ quan')),
            ],
            managers=[
                ('tchung', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchungcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
                ('codetrieuchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Trieuchung')),
            ],
            managers=[
                ('tccucbo', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Trieuchungtq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status1', models.CharField(default='1', max_length=2, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
                ('codetrieuchung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tctqs', to='center.Trieuchung')),
            ],
            managers=[
                ('trieuchungtqs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Typeservice',
            fields=[
                ('codeservice', models.CharField(default='DV', max_length=200, primary_key=True, serialize=False, verbose_name='Code service')),
                ('name_serv', models.CharField(choices=[('Chụp XQ', 'Chụp XQ'), ('Truyền máu', 'Truyền máu'), ('Điện não đồ', 'Điện não đồ'), ('Nội soi', 'Nội soi'), ('Siêu âm', 'Siêu âm')], max_length=200)),
            ],
            managers=[
                ('typeserv', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Xlkhancap',
            fields=[
                ('codexulykhancap', models.CharField(default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code Xử lý khẩn cấp')),
                ('name_xlkc', models.CharField(choices=[('Giảm đau bằng morphin', 'Giảm đau bằng morphin'), ('Trợ tim khẩn cấp', 'Trợ tim khẩn cấp'), ('Điện giải khẩn cấp', 'Điện giải khẩn cấp'), ('Truyền đạm', 'Truyền đạm')], default='Giảm đau bằng morphin', max_length=200, verbose_name='Tên xử lý khẩn cấp ')),
                ('status', models.CharField(default='Đã gửi yêu cầu', max_length=200, verbose_name='Trạng thái')),
                ('lankham', models.CharField(default='1', max_length=3, verbose_name='Lần khám')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('codepatient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient')),
            ],
            managers=[
                ('Xlkhancap1', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='codeservice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Typeservice'),
        ),
        migrations.AddField(
            model_name='ketluan',
            name='codepatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient'),
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='codepatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Patient'),
        ),
    ]
