# Generated by Django 2.1.5 on 2019-01-28 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namediv', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True, verbose_name='Is Active')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namepatient', models.CharField(max_length=200, verbose_name='Patient Name')),
                ('age', models.IntegerField(default=40, verbose_name='Age')),
                ('place', models.IntegerField(max_length=200, verbose_name='Place')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('description', models.TextField(verbose_name='Description')),
                ('Type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Division')),
            ],
        ),
    ]
