# Generated by Django 2.1.5 on 2019-02-14 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('codemedicine', models.CharField(choices=[('KS', 'Kháng sinh'), ('KV', 'Kháng viêm')], default='', max_length=200, primary_key=True, serialize=False, verbose_name='Code medicine')),
                ('name_medi', models.CharField(choices=[('Kháng sinh', 'Kháng sinh'), ('Kháng viêm', 'Kháng viêm')], max_length=200)),
                ('dosage', models.CharField(default='', max_length=200, verbose_name='Liều dùng')),
                ('function1', models.CharField(default='', max_length=200, verbose_name='Công dụng')),
                ('sideeffect', models.CharField(default='', max_length=200, verbose_name='Tác dụng phụ')),
            ],
            managers=[
                ('medi', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='donthuoc',
            name='codethuoc',
        ),
        migrations.RemoveField(
            model_name='donthuoc',
            name='name_donthuoc',
        ),
        migrations.AddField(
            model_name='donthuoc',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donthuoc',
            name='codedonthuoc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Medicine'),
        ),
    ]
