# Generated by Django 2.1.5 on 2019-01-28 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='place',
            field=models.CharField(max_length=200, verbose_name='Place'),
        ),
    ]
