# Generated by Django 2.1.5 on 2019-02-01 06:17

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190127_2258'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='division',
            managers=[
                ('div', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='patient',
            managers=[
                ('pat', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.TextField(default='', verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.CharField(default='', max_length=200, verbose_name='Doctor Name'),
        ),
        migrations.AddField(
            model_name='patient',
            name='symptom',
            field=models.TextField(default='', verbose_name='symptom'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
    ]
