# Generated by Django 2.1.5 on 2019-02-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_auto_20190214_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xlkhancap',
            name='codexulykhancap',
        ),
        migrations.AddField(
            model_name='xlkhancap',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicine',
            name='codemedicine',
            field=models.CharField(default='K', max_length=200, primary_key=True, serialize=False, verbose_name='Code medicine'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='function1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_medi',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sideeffect',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='xlkhancap',
            name='name_xlkc',
            field=models.CharField(max_length=200, verbose_name='Tên xử lý khẩn cấp '),
        ),
    ]
