# Generated by Django 2.1.5 on 2019-02-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20190214_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='function1',
            field=models.TextField(blank=True, null=True, verbose_name='Công dụng'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name_medi',
            field=models.CharField(max_length=200, verbose_name='Tên thuốc'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='sideeffect',
            field=models.TextField(blank=True, null=True, verbose_name='Tác dụng phụ'),
        ),
        migrations.AlterField(
            model_name='trieuchungtq',
            name='codepatient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codepatienttctq', to='center.Patient'),
        ),
        migrations.AlterField(
            model_name='trieuchungtq',
            name='codetrieuchung',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codetctqs', to='center.Trieuchung'),
        ),
    ]
