# Generated by Django 2.1.5 on 2019-02-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0003_auto_20190131_2217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='description',
            new_name='prescription',
        ),
        migrations.AlterField(
            model_name='patient',
            name='image',
            field=models.ImageField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
